version: '3.8'
services:
  mimic-pgadmin:
    image: 'dpage/pgadmin4:6'
    ports:
      - "8080:80" # "host:container"
    depends_on:
      - mimic-db
    networks:
      - default
    
    volumes:
      - mimic-pgadmin-data:/var/lib/pgadmin
    environment: 
      PGADMIN_DEFAULT_EMAIL: "${MIMIC_PGADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${MIMIC_PGADMIN_PASSWORD}"

  # Authentication
  mimic-db:
    image: 'postgres:14'
    ports:
      - "5432:5432"
    volumes:
      # Init
      - "${MIMIC_DIR_GIT}:/docker-entrypoint-initdb.d/"
      - "${MIMIC_DIR_GIT}/mimic_code:/mimic_code"
      # Datasets
      - "${MIMIC_DIR_IV}:/datasets/mimiciv_1_0"
      - "${MIMIC_DIR_ED}:/datasets/mimiciv_ed_1_0"
      # Database
      - "${MIMIC_DIR_DB}:/var/lib/postgresql/data"
    command:
      - "postgres"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "max_parallel_workers=${MIMIC_PG_PARALLEL}"
      - "-c"
      - "max_parallel_maintenance_workers=${MIMIC_PG_PARALLEL}"
      - "-c"
      - "max_parallel_workers_per_gather=${MIMIC_PG_PARALLEL}"
    user: "$DOCKER_UID:$DOCKER_GID" 
    
    environment: 
      POSTGRES_DB: "${MIMIC_DB}"
      POSTGRES_USER: "${MIMIC_USER}"
      POSTGRES_PASSWORD: "${MIMIC_PASSWORD}"
      POSTGRES_PARALLEL: "${MIMIC_PG_PARALLEL}"

networks:
 default:

volumes:
  mimic-pgadmin-data: