version: '3.8'
services:
  mimic-pgadmin:
    image: 'dpage/pgadmin4:6'
    ports:
      - "8080:80" # "host:container"
    depends_on:
      - mimic-db
    networks:
      - default
    
    volumes:
      - mimic-pgadmin-data:/var/lib/pgadmin
    environment: 
      PGADMIN_DEFAULT_EMAIL: "${MIMIC_PGADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${MIMIC_PGADMIN_PASSWORD}"

  # Authentication
  mimic-db:
    image: 'postgres:14'
    ports:
      - "5432:5432"
    volumes:
      - ./data/helpers/mimic_initdb:/docker-entrypoint-initdb.d
      - ./data/helpers/mimic_code:/mimic_code
      - ./data/datasets/mimiciv_1_0:/datasets/mimiciv_1_0
      - ./data/datasets/mimiciv_ed_1_0:/datasets/mimiciv_ed_1_0
      # - mimic-db-data:/var/lib/postgresql/data
      - ./data/transforms/mimic-db:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "maintenance_work_mem=512MB"
    
    environment: 
      POSTGRES_DB: "${MIMIC_DB}"
      POSTGRES_USER: "${MIMIC_USER}"
      POSTGRES_PASSWORD: "${MIMIC_PASSWORD}"

networks:
 default:

volumes:
  mimic-pgadmin-data:
  mimic-db-data: