version: '3.8'
services:
  mimic-pgadmin:
    image: 'dpage/pgadmin4:6'
    ports:
      - "8080:80" # "host:container"
    depends_on:
      - mimic-db
    networks:
      - default

  # Authentication
  mimic-db:
    image: 'postgres:14'
    volumes:
    #  - auth-data:/var/lib/mysql
    #  - ./:/workspace
    #command: echo "Hello World"
    
    environment: 
     POSTGRES_DB: "${MIMIC_DB}"
     POSTGRES_USER: "${MIMIC_USER}"
     POSTGRES_PASSWORD: "${MIMIC_PASSWORD}"

networks:
 default:

volumes:
  auth-data:
#  auth-db-data: